[package]
name = "linkspsql"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.19", features = ["full"] }
tokio-postgres = "0.7.6"
criterion = "0.3.6"
platform-data = "0.1.0-alpha.1"
doublets = "0.1.0-pre+beta.15"

[[bench]]
name = "bench"
harness = false
