name: Benchmark C++ version

on:
  push:
    branches:
      - add_cpp_benchmark

jobs:
  benchmark:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up CMake and Conan
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install utilities
        run: |
          sudo apt update
          sudo apt install -y cmake build-essential
          pip install conan
      - name: Set up Conan dependencies
        run: |
          conan profile detect
          echo "
          [settings]
          arch=x86_64
          build_type=Release
          compiler=gcc
          compiler.cppstd=gnu20
          compiler.libcxx=libstdc++11
          compiler.version=11
          os=Linux
          " > ~/.conan2/profiles/default
          conan profile show
      - name: Install dependencies
        run: |
          git clone https://github.com/linksplatform/conan-center-index
          cd conan-center-index && cd recipes
          conan create platform.interfaces/all --version 0.3.41
          conan create platform.delegates/all --version 0.3.7
          conan create platform.exceptions/all --version 0.3.2
          conan create platform.converters/all --version 0.2.0
          conan create platform.hashing/all --version 0.5.6 --build=missing
          conan create platform.ranges/all --version 0.2.0
          conan create platform.random/all --version 0.2.0
          conan create platform.equality/all --version 0.0.1
          conan create platform.collections/all --version 0.2.1
          conan create platform.setters/all --version 0.1.0
          conan create platform.data/all --version 0.1.1
          conan create platform.numbers/all --version 0.1.0
          conan create platform.memory/all --version 0.1.0 --build=missing
          conan create platform.collections.methods/all --version 0.3.0
          conan create platform.data.doublets/all --version 0.1.0
      - name: Build benchmark
        run: |
          cd cpp
          conan install . -of=build --build=missing
          cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=/home/runner/work/Comparisons.PostgreSQLVSDoublets/Comparisons.PostgreSQLVSDoublets/cpp/build/conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release -S . -B build
          cd build
          make
      - name: Run benchmark
        run: ./cpp/build/bin/PSQLBench --benchmark_out=cpp/out.txt --benchmark_out_format=console
      - name: Prepare benchmark results
        run: |
          cd cpp
          pip install numpy matplotlib
          python3 out.py
          git config --global user.email "linksplatform@gmail.com"
          git config --global user.name "LinksPlatformBencher"
          git fetch
          git checkout gh-pages
          mv bench_cpp.png ../Docs
          mv bench_cpp_log_scale.png ../Docs
          cd ..
          git add Docs
          git commit -m "Publish new benchmark results (C++)"
          git push origin gh-pages
      - name: Save benchmark results
        uses: actions/upload-artifact@v3
        with:
          name: Benchmark results
          path: |
            ../Docs/bench_cpp.png
            ../Docs/bench_cpp_log_scale.png
