name: Benchmark C++ version

on:
  push:
    branches:
      - add_cpp_benchmark

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up CMake and Conan
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install utilities
        run: |
          sudo apt update
          sudo apt install -y cmake build-essential
          pip install --force-reinstall -v "conan==1.59.0"
      - name: Setup Conan
        run: |
          conan profile new linksplatform --detect
          conan profile update settings.compiler.libcxx=libstdc++11 linksplatform
          conan profile show linksplatform
      - name: Install dependencies
        run: |  
          git clone https://github.com/linksplatform/conan-center-index
          cd conan-center-index && git checkout only-development && cd recipes
          conan create platform.interfaces/0.2.0+ platform.interfaces/0.2.5@ -pr=linksplatform
          conan create platform.converters/all platform.converters/0.1.0@ -pr=linksplatform
          conan create platform.ranges/all platform.ranges/0.1.3@ -pr=linksplatform
          conan create platform.random/all platform.random/0.1.0@ -pr=linksplatform
          conan create platform.collections/all platform.collections/0.1.0@ -pr=linksplatform
          conan create platform.collections.methods/all platform.collections.methods/0.1.0@ -pr=linksplatform
          conan create platform.converters/all platform.converters/0.1.0@ -pr=linksplatform
          conan create platform.threading/all platform.threading/0.1.0@ -pr=linksplatform
          conan create platform.memory/all platform.memory/0.1.0@ -pr=linksplatform
          conan create platform.setters/all platform.setters/0.0.1@ -pr=linksplatform
          conan create platform.data/all platform.data/0.1.0@ -pr=linksplatform
          conan create platform.delegates/all platform.delegates/0.1.3@ -pr=linksplatform
          conan create platform.equality/all platform.equality/0.0.1@ -pr=linksplatform
          conan create platform.exceptions/all platform.exceptions/0.3.0@ -pr=linksplatform
          conan create platform.hashing/all platform.hashing/0.2.0@ -pr=linksplatform
      - name: Build and run benchmark
        run: |
          cd cpp
          conan install . -if=build --build=missing -pr=linksplatform
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=/bin/make -G "CodeBlocks - Unix Makefiles" ..
          make
          ./bin/PSQLBench
